<a href="https://colab.research.google.com/github/koulkoudakis/tensorflow-fundamentals/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Sharome Burton

Aim: Cover some fundamental concepts of tensors using TensorFlow

Topics:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function
* Using GPU's with TensorFlow
* Exercises

## Introduction to Tensors


In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check number of dimensions of tensor (ndim)
scalar.ndim

0

In [6]:
# Create a vector (one dimension)
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check dimension of vector
vector.ndim

1

In [8]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10,18],
                      [18,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 18],
       [18,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [11]:
# Create new matrix
new_matrix = tf.constant([[10.,18.],
                      [18.,7.],
                      [4.,17.]], dtype=tf.float16) # specify data type
new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 18.],
       [18.,  7.],
       [ 4., 17.]], dtype=float16)>

In [12]:
new_matrix.ndim

2

In [13]:
# Create a tensor (more than two dimensions)
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

So far:

* Scalar: a single quantity
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector

### Creating tensors with `tf.Variable`

In [16]:
# Create tensor with tf.Variable()
changeable_tensor = tf.Variable([18,10])
unchangeable_tensor = tf.constant([18,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([18, 10], dtype=int32)>)

In [17]:
# Changing elements of tensors
changeable_tensor[0] = 7

TypeError: ignored

In [18]:
# using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [19]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [23]:
# Create two random (but same) tensors
random_1 = tf.random.Generator.from_seed(18) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(18)
random_2 = random_2.normal(shape=(3,2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.35877243, -1.9095894 ],
        [-0.2094769 ,  0.8286217 ],
        [-0.06695071, -0.35105535]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.35877243, -1.9095894 ],
        [-0.2094769 ,  0.8286217 ],
        [-0.06695071, -0.35105535]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)